---
title: "data_visualization"
author: "m_ahmed"
date: "2023-05-23"
output: html_document
---

```{r}

# Loading necessary libraries
library(tidyverse)
library(ggthemes)
library(ggrepel)
library(lubridate)

## Solution to Challenge 1 
covid_data_tbl <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv") %>% 
  select(location, date, total_cases) %>% 
  filter(location == "Germany" | location == "United Kingdom" | location == "France" |
           location == "Spain" | location == "United States" | location == "Europe") %>% 
  mutate(cases_format = scales::dollar(total_cases, big.mark = ".",
                                       decimal.mark = ",",
                                       prefix = "",
                                       suffix = ""))

covid_data_tbl %>% 
  
  ggplot(aes(x = date, y = total_cases, color = location)) +
  
  geom_line(size = 1) +
  geom_label_repel(aes(x = date, y = total_cases, label = cases_format, fill = location),
                   vjust = 0.7,
                   hjust = 1.2,
                   color = "white",
                   box.padding = 0.0,
                   min.segment.length = 0,
                   segment.color = "black",
                   data  = covid_data_tbl %>% slice(which.max(total_cases))) +
  
  guides(fill = FALSE) +
  
  expand_limits(y = 0) +
  
  scale_color_brewer(palette = "GnBu") +
  
  scale_y_continuous(labels = scales::dollar_format(scale = 1e-6,
                                                    prefix = "",
                                                    suffix = " M")) +
  
  scale_x_date(date_labels = "%B '%y",
               date_breaks = "1 month",
               expand = c(0, NA)) +
  
  labs(
    title = "COVID-19 confirmed cases worldwide",
    subtitle = "As of 21/05/2022",
    x = "",
    y = "Cumulative Cases",
    color = "Country"
  ) +
  
  theme_minimal() +
  theme(
    legend.position = "bottom",
    axis.title = element_text(face = "bold"),
    axis.text.x = element_text(angle = 45)
  )

```


```{r}
#part 02

library(tidyverse)
library(ggthemes)
library(ggrepel)
library(lubridate)
library(maps)

## Challenge 2
covid_data_tbl <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv") %>% 
  mutate(mortality_rate = total_deaths / population) %>% 
  group_by(location) %>% 
  summarise(latest_mort_rate = last(mortality_rate)) %>% 
  select(location, latest_mort_rate) %>% 
  mutate(location = case_when(
    
    location == "United Kingdom" ~ "UK",
    location == "United States" ~ "USA",
    location == "Democratic Republic of Congo" ~ "Democratic Republic of the Congo",
    TRUE ~ location
    
  )) %>%
  distinct()

world <- map_data("world")

covid_map <- merge(x = world, y = covid_data_tbl, by.x = "region", by.y = "location") %>% 
  select(region, long, lat, latest_mort_rate)

covid_map %>% 
  ggplot() +
  
  geom_map(aes(x = long, y = lat, map_id = region, fill = latest_mort_rate), map = world) +
  
  borders("world", colour = "grey85") +
  
  scale_fill_continuous(labels = scales::percent_format(accuracy = 0.001), 
                        low = "yellow",
                         high = "darkred")+
              
  
  labs(
    title = "Confirmed COVID-19 fatalities in relation to population size",
    subtitle = "Around 6.2 million COVID-19 deaths have been confirmed globally.",
    caption = "Date: 22-May-2023",
    fill = "Rate of Mortality"
  ) +
  
  theme_minimal() +
  
  theme(
    axis.line = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    title = element_text(color = "red"),
    legend.position = "right"
  )

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
